-keep class com.op.aod.enhance.HookEntryXposed { *; }
-keep class com.highcapable.yukihookapi.** { *; }
-keep class com.highcapable.kavaref.** { *; }
-keep class top.yukonga.miuix.** { *; }
-dontwarn com.highcapable.**
-dontwarn top.yukonga.miuix.**
